### ISSUE TITLE
Issues found by OSS Fuzz

### ISSUE THREAD

**Issue by offa** [jhy/jsoup#1537]
Issues found by [oss-fuzz](https://github.com/google/oss-fuzz):

- [x] #1538 :warning: Affects fuzzing
- [x] #1539 :warning: Affects fuzzing
- [x] #1540
- [x] #1541 :warning: Affects fuzzing
- [x] #1542 :warning: Affects fuzzing
- [x] #1543
- [x] #1544
- [x] #1545
- [x] #1546
- [x] #1548 
- [x] #1566

Please let me know, if someone is interested in fixing an issue so can provide further information.

Related: #1502 

/cc @jhy

**Comment by krystiangorecki** [comment]
I may be interested, can you report all of them here as separate issues?

**Comment by offa** [comment]
Yes, on the way …

**Comment by jhy** [comment]
Have fixed a couple of these - but having difficulty reproducing #1542. Anyone else able to repro?

**Comment by jhy** [comment]
Thanks - closing this out as all of these are fixed now. Will monitor for incoming and file.

**Comment by offa** [comment]
Awesome! 😃

**Comment by 0roman** [comment]
Hi @jhy, it is really great to see how fast you are fixing the issues that were found with fuzzing, great to have you! 

Some bugs found seem to have security impact, for example, the attack scenario of an out of memory during parsing of html/xml could lead to denial of service. Do you plan publishing security advisories for these? If not, we could assist and could do that.

**Comment by jhy** [comment]
Thanks @0roman  -- yes I've been making good progress through them and really happy to have the fuzzer running. I think it's catching issues that people have seen perhaps in the wild once or twice during large spidering runs but have never been able to repro.

I think it might make sense to publish a catch-all advisory to help notify people. I'd appreciate your help on that. Would you mind contacting me directly (jonathan@hedley.net)?

**Comment by 0roman** [comment]
Hi @jhy, I contacted you on 20th of July from wagner@code-intelligence.com. It would be great if we could discuss further actions.

**Comment by jhy** [comment]
Ack; replied, sorry I missed earlier!
